//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnivesShop.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KnivesShop.Web.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lv.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shopping cart is empty.
        /// </summary>
        public static string EmptyBasket {
            get {
                return ResourceManager.GetString("EmptyBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the text from the picture.
        /// </summary>
        public static string EnterCaptcha {
            get {
                return ResourceManager.GetString("EnterCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops...  something wrong happend!.
        /// </summary>
        public static string ErroPage {
            get {
                return ResourceManager.GetString("ErroPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to page:.
        /// </summary>
        public static string GoToPage {
            get {
                return ResourceManager.GetString("GoToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching the criterias articles found.
        /// </summary>
        public static string NoArticlesFound {
            get {
                return ResourceManager.GetString("NoArticlesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No articles with this category for the moment.
        /// </summary>
        public static string NoArticlesInTheCategory {
            get {
                return ResourceManager.GetString("NoArticlesInTheCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price of all products.
        /// </summary>
        public static string PriceOfAllProducts {
            get {
                return ResourceManager.GetString("PriceOfAllProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshCaptcha {
            get {
                return ResourceManager.GetString("RefreshCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select category.
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Price.
        /// </summary>
        public static string SelectPrice {
            get {
                return ResourceManager.GetString("SelectPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping cart.
        /// </summary>
        public static string ShopingCart {
            get {
                return ResourceManager.GetString("ShopingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total price.
        /// </summary>
        public static string TotalProductPrice {
            get {
                return ResourceManager.GetString("TotalProductPrice", resourceCulture);
            }
        }
    }
}
